In [34]:
import numpy as np
import copy

In [35]:

a = np.arange(16).reshape(4, 4)

print("a:")
print(a, end="\n\n")


a:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



In [36]:
b = a
print("b = a:")
print(b, end="\n\n")

b[0, 0] = 14111

print("a:")
print(a)
print("b:")
print(b, end="\n\n")


b = a:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

a:
[[14111     1     2     3]
 [    4     5     6     7]
 [    8     9    10    11]
 [   12    13    14    15]]
b:
[[14111     1     2     3]
 [    4     5     6     7]
 [    8     9    10    11]
 [   12    13    14    15]]



In [37]:
a = np.arange(16).reshape(4, 4)
b = a.view()

print("b = a.view():")
print(b, end="\n\n")

b[0, 1] = 1231

print("a:")
print(a)
print("b:")
print(b, end="\n\n")


b = a.view():
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

a:
[[   0 1231    2    3]
 [   4    5    6    7]
 [   8    9   10   11]
 [  12   13   14   15]]
b:
[[   0 1231    2    3]
 [   4    5    6    7]
 [   8    9   10   11]
 [  12   13   14   15]]



In [38]:
a = np.arange(16).reshape(4, 4)
b = a.copy()

print("b = a.copy():")
print(b, end="\n\n")

b[0, 2] = 33333

print("a:")
print(a)
print("b:")
print(b, end="\n\n")


b = a.copy():
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

a:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
b:
[[    0     1 33333     3]
 [    4     5     6     7]
 [    8     9    10    11]
 [   12    13    14    15]]



In [41]:
a = np.array([
    [[1], [2]],
    [[3], [4]]
], dtype=object)

b = a.copy()
c = copy.deepcopy(a)

print(a, end="\n\n")

b[0, 0].append(999)

print("a:")
print(a)
print("b:")
print(b)
print("c (deepcopy):")
print(c)


[[[1]
  [2]]

 [[3]
  [4]]]



AttributeError: 'numpy.ndarray' object has no attribute 'append'